import { Order, OrderStatus, DeliveryService } from '@/types';

// Generate mock orders for demo
export const MOCK_ORDERS: Order[] = [
  {
    id: '1',
    ticketCode: 'LC-2024-001',
    qrCode: 'qr_lc_001',
    customerId: 'c1',
    customerName: 'María García',
    customerPhone: '+52 55 1234 5678',
    customerAddress: 'Av. Reforma 123, Col. Centro',
    items: [
      { id: 'i1', name: 'Lavado + Secado', type: 'weight', quantity: 3.5, unitPrice: 5.00, extras: ['Suavizante Premium'] },
      { id: 'i2', name: 'Planchado Camisas', type: 'piece', quantity: 4, unitPrice: 2.50, extras: [] },
    ],
    status: 'washing',
    totalAmount: 29.50,
    paidAmount: 29.50,
    isPaid: true,
    isDelivery: true,
    deliverySlot: 'afternoon',
    needsPickup: false,
    needsDelivery: true,
    pickupService: undefined,
    deliveryService: {
      type: 'delivery',
      status: 'pending',
      scheduledSlot: 'afternoon',
      address: 'Av. Reforma 123, Col. Centro',
    },
    createdAt: new Date('2024-01-08T09:30:00'),
    updatedAt: new Date('2024-01-08T11:00:00'),
    estimatedReadyAt: new Date('2024-01-08T16:00:00'),
    notes: 'Cliente VIP, cuidado con la camisa azul',
  },
  {
    id: '2',
    ticketCode: 'LC-2024-002',
    qrCode: 'qr_lc_002',
    customerId: 'c2',
    customerName: 'Juan López',
    customerPhone: '+52 55 9876 5432',
    customerAddress: 'Calle Insurgentes 456, Zona Rosa',
    items: [
      { id: 'i3', name: 'Lavado en Seco', type: 'piece', quantity: 2, unitPrice: 12.00, extras: ['Desmanchado'] },
    ],
    status: 'pending_pickup',
    totalAmount: 27.00,
    paidAmount: 0,
    isPaid: false,
    isDelivery: true,
    deliverySlot: 'morning',
    needsPickup: true,
    needsDelivery: true,
    pickupService: {
      type: 'pickup',
      status: 'pending',
      scheduledSlot: 'morning',
      address: 'Calle Insurgentes 456, Zona Rosa',
      notes: 'Tocar timbre 2B',
    },
    deliveryService: {
      type: 'delivery',
      status: 'pending',
      scheduledSlot: 'afternoon',
      address: 'Calle Insurgentes 456, Zona Rosa',
    },
    createdAt: new Date('2024-01-08T08:00:00'),
    updatedAt: new Date('2024-01-08T08:00:00'),
    notes: 'Recoger y entregar en casa del cliente',
  },
  {
    id: '3',
    ticketCode: 'LC-2024-003',
    qrCode: 'qr_lc_003',
    customerId: 'c3',
    customerName: 'Ana Martínez',
    customerPhone: '+52 55 5555 1234',
    items: [
      { id: 'i4', name: 'Lavado + Secado + Planchado', type: 'weight', quantity: 5, unitPrice: 8.00, extras: [] },
    ],
    status: 'ready_delivery',
    totalAmount: 40.00,
    paidAmount: 40.00,
    isPaid: true,
    isDelivery: false,
    needsPickup: false,
    needsDelivery: false,
    createdAt: new Date('2024-01-07T14:00:00'),
    updatedAt: new Date('2024-01-08T10:30:00'),
    estimatedReadyAt: new Date('2024-01-08T10:00:00'),
  },
  {
    id: '4',
    ticketCode: 'LC-2024-004',
    qrCode: 'qr_lc_004',
    customerId: 'c4',
    customerName: 'Roberto Sánchez',
    customerPhone: '+52 55 4444 3333',
    customerAddress: 'Calle Durango 45, Roma Norte',
    items: [
      { id: 'i5', name: 'Lavado + Secado', type: 'weight', quantity: 8, unitPrice: 5.00, extras: ['Suavizante Premium', 'Servicio Express'] },
      { id: 'i6', name: 'Desmanchado', type: 'piece', quantity: 3, unitPrice: 3.00, extras: [] },
    ],
    status: 'in_transit',
    totalAmount: 61.00,
    paidAmount: 61.00,
    isPaid: true,
    isDelivery: true,
    deliverySlot: 'afternoon',
    deliveryDriverId: '4',
    needsPickup: false,
    needsDelivery: true,
    deliveryService: {
      type: 'delivery',
      status: 'in_progress',
      driverId: '4',
      scheduledSlot: 'afternoon',
      address: 'Calle Durango 45, Roma Norte',
    },
    createdAt: new Date('2024-01-07T09:00:00'),
    updatedAt: new Date('2024-01-08T14:00:00'),
    deliveredAt: undefined,
  },
  {
    id: '5',
    ticketCode: 'LC-2024-005',
    qrCode: 'qr_lc_005',
    customerId: 'c5',
    customerName: 'Laura Hernández',
    customerPhone: '+52 55 2222 1111',
    items: [
      { id: 'i7', name: 'Lavado + Secado', type: 'weight', quantity: 2.5, unitPrice: 5.00, extras: [] },
    ],
    status: 'drying',
    totalAmount: 12.50,
    paidAmount: 12.50,
    isPaid: true,
    isDelivery: false,
    needsPickup: false,
    needsDelivery: false,
    createdAt: new Date('2024-01-08T10:00:00'),
    updatedAt: new Date('2024-01-08T12:30:00'),
    estimatedReadyAt: new Date('2024-01-08T15:00:00'),
  },
  {
    id: '6',
    ticketCode: 'LC-2024-006',
    qrCode: 'qr_lc_006',
    customerId: 'c6',
    customerName: 'Carlos Ruiz',
    customerPhone: '+52 55 6666 7777',
    customerAddress: 'Insurgentes Sur 800',
    items: [
      { id: 'i8', name: 'Lavado en Seco', type: 'piece', quantity: 5, unitPrice: 12.00, extras: [] },
    ],
    status: 'delivered',
    totalAmount: 60.00,
    paidAmount: 60.00,
    isPaid: true,
    isDelivery: true,
    deliverySlot: 'morning',
    deliveryDriverId: '4',
    needsPickup: true,
    needsDelivery: true,
    pickupService: {
      type: 'pickup',
      status: 'completed',
      driverId: '4',
      scheduledSlot: 'morning',
      address: 'Insurgentes Sur 800',
      completedAt: new Date('2024-01-06T11:30:00'),
    },
    deliveryService: {
      type: 'delivery',
      status: 'completed',
      driverId: '4',
      scheduledSlot: 'morning',
      address: 'Insurgentes Sur 800',
      completedAt: new Date('2024-01-07T10:00:00'),
    },
    createdAt: new Date('2024-01-06T11:00:00'),
    updatedAt: new Date('2024-01-07T10:00:00'),
    deliveredAt: new Date('2024-01-07T10:00:00'),
  },
  {
    id: '7',
    ticketCode: 'LC-2024-007',
    qrCode: 'qr_lc_007',
    customerId: 'c7',
    customerName: 'Patricia Morales',
    customerPhone: '+52 55 8888 9999',
    items: [
      { id: 'i9', name: 'Lavado + Secado + Planchado', type: 'weight', quantity: 4, unitPrice: 8.00, extras: ['Suavizante Premium'] },
      { id: 'i10', name: 'Planchado Camisas', type: 'piece', quantity: 6, unitPrice: 2.50, extras: [] },
    ],
    status: 'ironing',
    totalAmount: 49.00,
    paidAmount: 25.00,
    isPaid: false,
    isDelivery: false,
    needsPickup: false,
    needsDelivery: false,
    createdAt: new Date('2024-01-08T08:30:00'),
    updatedAt: new Date('2024-01-08T13:00:00'),
    estimatedReadyAt: new Date('2024-01-08T17:00:00'),
    notes: 'Pago parcial, cobra el resto al entregar',
  },
  {
    id: '8',
    ticketCode: 'LC-2024-008',
    qrCode: 'qr_lc_008',
    customerId: 'c8',
    customerName: 'Fernando Castro',
    customerPhone: '+52 55 1111 0000',
    customerAddress: 'Polanco, Miguel Hidalgo 234',
    items: [
      { id: 'i11', name: 'Lavado + Secado', type: 'weight', quantity: 6, unitPrice: 5.00, extras: ['Servicio Express'] },
    ],
    status: 'in_store',
    totalAmount: 40.00,
    paidAmount: 40.00,
    isPaid: true,
    isDelivery: true,
    deliverySlot: 'afternoon',
    needsPickup: false,
    needsDelivery: true,
    deliveryService: {
      type: 'delivery',
      status: 'pending',
      scheduledSlot: 'afternoon',
      address: 'Polanco, Miguel Hidalgo 234',
    },
    createdAt: new Date('2024-01-08T11:00:00'),
    updatedAt: new Date('2024-01-08T11:30:00'),
    estimatedReadyAt: new Date('2024-01-08T14:00:00'),
  },
  {
    id: '9',
    ticketCode: 'LC-2024-009',
    qrCode: 'qr_lc_009',
    customerId: 'c9',
    customerName: 'Diana Torres',
    customerPhone: '+52 55 3333 2222',
    customerAddress: 'Condesa, Av. Amsterdam 78',
    items: [
      { id: 'i12', name: 'Lavado + Secado', type: 'weight', quantity: 4, unitPrice: 5.00, extras: [] },
    ],
    status: 'pending_pickup',
    totalAmount: 20.00,
    paidAmount: 0,
    isPaid: false,
    isDelivery: true,
    deliverySlot: 'afternoon',
    needsPickup: true,
    needsDelivery: false,
    pickupService: {
      type: 'pickup',
      status: 'assigned',
      driverId: '2',
      scheduledSlot: 'afternoon',
      address: 'Condesa, Av. Amsterdam 78',
      notes: 'Dejar en recepción',
    },
    createdAt: new Date('2024-01-08T09:00:00'),
    updatedAt: new Date('2024-01-08T09:30:00'),
    notes: 'Solo recogida, cliente pasará por la ropa',
  },
];

// Helper to get orders by status
export const getOrdersByStatus = (status: OrderStatus): Order[] => {
  return MOCK_ORDERS.filter(order => order.status === status);
};

// Helper to get order counts by status
export const getOrderCountsByStatus = (): Record<OrderStatus, number> => {
  const counts: Record<string, number> = {};
  MOCK_ORDERS.forEach(order => {
    counts[order.status] = (counts[order.status] || 0) + 1;
  });
  return counts as Record<OrderStatus, number>;
};
