import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { toast } from 'sonner';
import { X, MapPin, Clock, Package, Check } from 'lucide-react';

interface NewPickupRequestProps {
  customerId?: string;
  userId: string;
  onClose: () => void;
}

interface Address {
  id: string;
  label: string;
  address: string;
  delivery_instructions?: string;
  is_default: boolean;
}

interface Service {
  id: string;
  name: string;
  price: number;
  unit: string;
  category: string;
}

export default function NewPickupRequest({ customerId, userId, onClose }: NewPickupRequestProps) {
  const [step, setStep] = useState(1);
  const [addresses, setAddresses] = useState<Address[]>([]);
  const [services, setServices] = useState<Service[]>([]);
  const [selectedAddress, setSelectedAddress] = useState<Address | null>(null);
  const [selectedServices, setSelectedServices] = useState<string[]>([]);
  const [pickupSlot, setPickupSlot] = useState('');
  const [notes, setNotes] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    fetchAddresses();
    fetchServices();
  }, [userId]);

  const fetchAddresses = async () => {
    const { data } = await supabase
      .from('customer_addresses')
      .select('*')
      .eq('customer_id', userId)
      .order('is_default', { ascending: false });

    setAddresses(data || []);
    if (data && data.length > 0) {
      setSelectedAddress(data.find(a => a.is_default) || data[0]);
    }
  };

  const fetchServices = async () => {
    const { data } = await supabase
      .from('catalog_services')
      .select('*')
      .eq('is_active', true)
      .order('category');

    setServices(data || []);
  };

  const timeSlots = [
    '08:00 - 10:00',
    '10:00 - 12:00',
    '12:00 - 14:00',
    '14:00 - 16:00',
    '16:00 - 18:00',
    '18:00 - 20:00',
  ];

  const toggleService = (serviceId: string) => {
    setSelectedServices(prev => 
      prev.includes(serviceId) 
        ? prev.filter(id => id !== serviceId)
        : [...prev, serviceId]
    );
  };

  const handleSubmit = async () => {
    if (!selectedAddress) {
      toast.error('Selecciona una dirección de recogida');
      return;
    }

    if (!pickupSlot) {
      toast.error('Selecciona un horario de recogida');
      return;
    }

    setIsLoading(true);

    try {
      // Get customer data
      const { data: customer } = await supabase
        .from('customers')
        .select('*')
        .eq('user_id', userId)
        .single();

      if (!customer) {
        toast.error('Error al obtener datos del cliente');
        return;
      }

      // Create order
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
          ticket_code: 'TEMP', // Will be generated by trigger
          customer_id: customer.id,
          customer_name: customer.name,
          customer_phone: customer.phone,
          customer_address: selectedAddress.address,
          pickup_address: selectedAddress.address,
          pickup_slot: pickupSlot,
          needs_pickup: true,
          needs_delivery: true,
          delivery_address: selectedAddress.address,
          status: 'pending_pickup',
          notes: notes || null,
          total_amount: 0, // Will be calculated when items are added
        })
        .select()
        .single();

      if (orderError) throw orderError;

      // Add order items if services selected
      if (selectedServices.length > 0 && order) {
        const orderItems = selectedServices.map(serviceId => {
          const service = services.find(s => s.id === serviceId);
          return {
            order_id: order.id,
            service_id: serviceId,
            name: service?.name || '',
            quantity: 1,
            unit_price: service?.price || 0,
            item_type: 'weight' as const,
          };
        });

        await supabase.from('order_items').insert(orderItems);
      }

      toast.success('¡Solicitud de recogida creada!');
      onClose();
    } catch (error) {
      console.error('Error creating pickup request:', error);
      toast.error('Error al crear la solicitud');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/50 flex items-end justify-center sm:items-center">
      <div className="bg-background w-full max-w-lg rounded-t-2xl sm:rounded-2xl max-h-[90vh] overflow-auto animate-in slide-in-from-bottom">
        {/* Header */}
        <div className="sticky top-0 bg-background p-4 border-b flex items-center justify-between z-10">
          <h2 className="font-bold text-lg">Solicitar Recogida</h2>
          <button onClick={onClose} className="p-2 hover:bg-muted rounded-lg">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Progress Steps */}
        <div className="flex items-center justify-center gap-2 p-4 border-b">
          {[1, 2, 3].map(s => (
            <div
              key={s}
              className={`w-3 h-3 rounded-full transition-colors ${
                s <= step ? 'bg-primary' : 'bg-muted'
              }`}
            />
          ))}
        </div>

        <div className="p-4">
          {/* Step 1: Select Address */}
          {step === 1 && (
            <div className="space-y-4">
              <div className="flex items-center gap-2 mb-4">
                <MapPin className="w-5 h-5 text-primary" />
                <h3 className="font-semibold">Dirección de Recogida</h3>
              </div>

              {addresses.length === 0 ? (
                <Card>
                  <CardContent className="p-6 text-center text-muted-foreground">
                    <p>No tienes direcciones guardadas</p>
                    <p className="text-sm">Agrega una en la pestaña "Direcciones"</p>
                  </CardContent>
                </Card>
              ) : (
                <div className="space-y-3">
                  {addresses.map(addr => (
                    <Card 
                      key={addr.id}
                      className={`cursor-pointer transition-all ${
                        selectedAddress?.id === addr.id 
                          ? 'border-primary ring-2 ring-primary/20' 
                          : 'hover:border-primary/50'
                      }`}
                      onClick={() => setSelectedAddress(addr)}
                    >
                      <CardContent className="p-4 flex items-center gap-3">
                        <div className={`w-5 h-5 rounded-full border-2 flex items-center justify-center ${
                          selectedAddress?.id === addr.id 
                            ? 'border-primary bg-primary' 
                            : 'border-muted-foreground'
                        }`}>
                          {selectedAddress?.id === addr.id && (
                            <Check className="w-3 h-3 text-primary-foreground" />
                          )}
                        </div>
                        <div className="flex-1">
                          <p className="font-medium">{addr.label}</p>
                          <p className="text-sm text-muted-foreground">{addr.address}</p>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              )}

              <Button 
                className="w-full mt-4" 
                onClick={() => setStep(2)}
                disabled={!selectedAddress}
              >
                Continuar
              </Button>
            </div>
          )}

          {/* Step 2: Select Time Slot */}
          {step === 2 && (
            <div className="space-y-4">
              <div className="flex items-center gap-2 mb-4">
                <Clock className="w-5 h-5 text-primary" />
                <h3 className="font-semibold">Horario de Recogida</h3>
              </div>

              <div className="grid grid-cols-2 gap-3">
                {timeSlots.map(slot => (
                  <Card 
                    key={slot}
                    className={`cursor-pointer transition-all ${
                      pickupSlot === slot 
                        ? 'border-primary ring-2 ring-primary/20' 
                        : 'hover:border-primary/50'
                    }`}
                    onClick={() => setPickupSlot(slot)}
                  >
                    <CardContent className="p-4 text-center">
                      <p className={`font-medium ${pickupSlot === slot ? 'text-primary' : ''}`}>
                        {slot}
                      </p>
                    </CardContent>
                  </Card>
                ))}
              </div>

              <div className="flex gap-2 mt-4">
                <Button variant="outline" onClick={() => setStep(1)} className="flex-1">
                  Atrás
                </Button>
                <Button 
                  onClick={() => setStep(3)}
                  disabled={!pickupSlot}
                  className="flex-1"
                >
                  Continuar
                </Button>
              </div>
            </div>
          )}

          {/* Step 3: Services & Notes */}
          {step === 3 && (
            <div className="space-y-4">
              <div className="flex items-center gap-2 mb-4">
                <Package className="w-5 h-5 text-primary" />
                <h3 className="font-semibold">Servicios (opcional)</h3>
              </div>

              <p className="text-sm text-muted-foreground mb-4">
                Selecciona los servicios que necesitas. El precio final se calculará cuando pesemos tus prendas.
              </p>

              <div className="space-y-2 max-h-48 overflow-auto">
                {services.map(service => (
                  <Card 
                    key={service.id}
                    className={`cursor-pointer transition-all ${
                      selectedServices.includes(service.id) 
                        ? 'border-primary ring-2 ring-primary/20' 
                        : 'hover:border-primary/50'
                    }`}
                    onClick={() => toggleService(service.id)}
                  >
                    <CardContent className="p-3 flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className={`w-5 h-5 rounded border-2 flex items-center justify-center ${
                          selectedServices.includes(service.id) 
                            ? 'border-primary bg-primary' 
                            : 'border-muted-foreground'
                        }`}>
                          {selectedServices.includes(service.id) && (
                            <Check className="w-3 h-3 text-primary-foreground" />
                          )}
                        </div>
                        <span className="font-medium">{service.name}</span>
                      </div>
                      <span className="text-sm text-muted-foreground">
                        ${service.price}/{service.unit}
                      </span>
                    </CardContent>
                  </Card>
                ))}
              </div>

              <div className="space-y-2">
                <Label>Notas adicionales</Label>
                <textarea
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                  placeholder="Instrucciones especiales, prendas delicadas, etc."
                  className="w-full p-3 border rounded-lg min-h-[80px] resize-none"
                />
              </div>

              {/* Summary */}
              <Card className="bg-muted/50">
                <CardContent className="p-4 space-y-2">
                  <h4 className="font-semibold">Resumen</h4>
                  <div className="text-sm space-y-1">
                    <p><strong>Dirección:</strong> {selectedAddress?.address}</p>
                    <p><strong>Horario:</strong> {pickupSlot}</p>
                    {selectedServices.length > 0 && (
                      <p><strong>Servicios:</strong> {selectedServices.length} seleccionados</p>
                    )}
                  </div>
                </CardContent>
              </Card>

              <div className="flex gap-2">
                <Button variant="outline" onClick={() => setStep(2)} className="flex-1">
                  Atrás
                </Button>
                <Button 
                  onClick={handleSubmit}
                  disabled={isLoading}
                  className="flex-1"
                >
                  {isLoading ? 'Enviando...' : 'Confirmar Recogida'}
                </Button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
